function out1 = Ath_fun(I1,I2,I3,a1,a3,l1,l2,lc1,lc2,lc3,m1,m2,m3)
%ATH_FUN
%    OUT1 = ATH_FUN(I1,I2,I3,A1,A3,L1,L2,LC1,LC2,LC3,M1,M2,M3)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    26-Feb-2016 22:57:17

t2 = cos(a1);
t3 = l1.^2;
t4 = t2.^2;
t5 = lc1.^2;
t6 = sin(a1);
t7 = t6.^2;
t8 = cos(a3);
t9 = sin(a3);
t10 = l2.^2;
t11 = lc2.^2;
t12 = m1.*m2.*t3.*t4;
t13 = m1.*m3.*t3.*t4;
t14 = m1.*m2.*t4.*t5;
t15 = m1.*m3.*t4.*t5;
t16 = lc3.^2;
t17 = t8.^2;
t18 = m1.*m2.*t3.*t7;
t19 = m1.*m3.*t3.*t7;
t20 = m1.*m2.*t5.*t7;
t21 = m1.*m3.*t5.*t7;
t22 = t9.^2;
t23 = m1.*m3.*t16.*t17;
t24 = m2.*m3.*t16.*t17;
t25 = m1.*m3.*t16.*t22;
t26 = m2.*m3.*t16.*t22;
t27 = l1.*lc3.*m1.*m3.*t2.*t8;
t28 = lc1.*lc3.*m1.*m3.*t6.*t9;
t29 = I1.*m1;
t30 = I1.*m2;
t31 = I2.*m1;
t32 = I1.*m3;
t33 = I2.*m2;
t34 = I3.*m1;
t35 = I2.*m3;
t36 = I3.*m2;
t37 = I3.*m3;
t38 = m1.*m3.*t10;
t39 = m2.*m3.*t10;
t40 = m1.*m2.*t11;
t41 = m2.*m3.*t11;
t42 = l1.*l2.*m1.*m3.*t2.*2.0;
t43 = l1.*lc2.*m1.*m2.*t2.*2.0;
t44 = l2.*lc3.*m1.*m3.*t8.*2.0;
t45 = l2.*lc3.*m2.*m3.*t8.*2.0;
t46 = l1.*lc3.*m1.*m3.*t2.*t8.*2.0;
t47 = lc1.*lc3.*m1.*m3.*t6.*t9.*2.0;
t48 = t12+t13+t14+t15+t18+t19+t20+t21+t23+t24+t25+t26+t29+t30+t31+t32+t33+t34+t35+t36+t37+t38+t39+t40+t41+t42+t43+t44+t45+t46+t47-l2.*lc2.*m2.*m3.*2.0-l1.*lc1.*m1.*m2.*t4.*2.0-l2.*lc1.*m1.*m3.*t2.*2.0-l1.*lc1.*m1.*m3.*t4.*2.0-l1.*lc1.*m1.*m2.*t7.*2.0-l1.*lc1.*m1.*m3.*t7.*2.0-lc1.*lc2.*m1.*m2.*t2.*2.0-lc2.*lc3.*m2.*m3.*t8.*2.0-l1.*lc3.*m1.*m3.*t6.*t9.*2.0-lc1.*lc3.*m1.*m3.*t2.*t8.*2.0;
t49 = 1.0./t48;
out1 = [-t49.*(t12+t13+t14+t15+t18+t19+t20+t21+t27+t28+l1.*l2.*m1.*m3.*t2+l1.*lc2.*m1.*m2.*t2-l1.*lc1.*m1.*m2.*t4.*2.0-l2.*lc1.*m1.*m3.*t2-l1.*lc1.*m1.*m3.*t4.*2.0-l1.*lc1.*m1.*m2.*t7.*2.0-l1.*lc1.*m1.*m3.*t7.*2.0-lc1.*lc2.*m1.*m2.*t2-l1.*lc3.*m1.*m3.*t6.*t9-lc1.*lc3.*m1.*m3.*t2.*t8),t49.*(t23+t24+t25+t26+t27+t28+l2.*lc3.*m1.*m3.*t8+l2.*lc3.*m2.*m3.*t8-lc2.*lc3.*m2.*m3.*t8-l1.*lc3.*m1.*m3.*t6.*t9-lc1.*lc3.*m1.*m3.*t2.*t8)];
