function drift_th = Drift_theta_fun(I1,I2,I3,a1,a3,gen_mom_x,gen_mom_y,gen_mom_th,l1,l2,lc1,lc2,lc3,m1,m2,m3)
%DRIFT_THETA_FUN
%    DRIFT_TH = DRIFT_THETA_FUN(I1,I2,I3,A1,A3,GEN_MOM_X,GEN_MOM_Y,GEN_MOM_TH,L1,L2,LC1,LC2,LC3,M1,M2,M3)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    26-Feb-2016 22:57:16

t2 = cos(a1);
t3 = sin(a1);
t4 = l2.^2;
t5 = lc2.^2;
t6 = l1.^2;
t7 = t2.^2;
t8 = lc1.^2;
t9 = cos(a3);
t10 = lc3.^2;
t11 = t9.^2;
t12 = t3.^2;
t13 = sin(a3);
t14 = t13.^2;
drift_th = (gen_mom_th.*m1+gen_mom_th.*m2+gen_mom_th.*m3-gen_mom_x.*l2.*m3+gen_mom_x.*lc2.*m1+gen_mom_x.*lc2.*m3+gen_mom_x.*l1.*m1.*t2+gen_mom_y.*l1.*m1.*t3-gen_mom_x.*lc1.*m1.*t2-gen_mom_y.*lc1.*m1.*t3-gen_mom_x.*lc3.*m3.*t9+gen_mom_y.*lc3.*m3.*t13)./(I1.*m1+I1.*m2+I2.*m1+I1.*m3+I2.*m2+I3.*m1+I2.*m3+I3.*m2+I3.*m3+m1.*m2.*t5+m1.*m3.*t4+m2.*m3.*t4+m2.*m3.*t5-l2.*lc2.*m2.*m3.*2.0+m1.*m2.*t6.*t7+m1.*m3.*t6.*t7+m1.*m2.*t7.*t8+m1.*m3.*t7.*t8+m1.*m2.*t6.*t12+m1.*m3.*t6.*t12+m1.*m2.*t8.*t12+m1.*m3.*t8.*t12+m1.*m3.*t10.*t11+m2.*m3.*t10.*t11+m1.*m3.*t10.*t14+m2.*m3.*t10.*t14+l1.*l2.*m1.*m3.*t2.*2.0+l1.*lc2.*m1.*m2.*t2.*2.0-l2.*lc1.*m1.*m3.*t2.*2.0-l1.*lc1.*m1.*m2.*t7.*2.0-l1.*lc1.*m1.*m3.*t7.*2.0-l1.*lc1.*m1.*m2.*t12.*2.0-l1.*lc1.*m1.*m3.*t12.*2.0+l2.*lc3.*m1.*m3.*t9.*2.0+l2.*lc3.*m2.*m3.*t9.*2.0-lc1.*lc2.*m1.*m2.*t2.*2.0-lc2.*lc3.*m2.*m3.*t9.*2.0+l1.*lc3.*m1.*m3.*t2.*t9.*2.0-l1.*lc3.*m1.*m3.*t3.*t13.*2.0-lc1.*lc3.*m1.*m3.*t2.*t9.*2.0+lc1.*lc3.*m1.*m3.*t3.*t13.*2.0);
