function Ir = Ir_fun(I1,I2,I3,a1,a3,l1,l2,lc1,lc2,lc3,m1,m2,m3)
%IR_FUN
%    IR = IR_FUN(I1,I2,I3,A1,A3,L1,L2,LC1,LC2,LC3,M1,M2,M3)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    26-Feb-2016 22:57:06

t2 = m1+m2+m3;
t3 = l1-lc1;
t4 = cos(a1);
t5 = t3.*t4;
t6 = lc2+t5;
t7 = cos(a3);
t8 = lc3.*t7;
t9 = l2-lc2+t8;
t10 = m3.*t9;
t11 = t10-m1.*t6;
t12 = sin(a3);
t13 = sin(a1);
t14 = -lc3.*m3.*t12-m1.*t3.*t13;
Ir = reshape([t2,0.0,t11,0.0,t2,t14,t11,t14,I1+I2+I3+m1.*t6.^2+m3.*t9.^2+lc3.^2.*m3.*t12.^2+m1.*t3.^2.*t13.^2],[3,3]);
