function Js = Js_fun(I1,I3,a1,a3,l1,lc1,lc3,m1,m3)
%JS_FUN
%    JS = JS_FUN(I1,I3,A1,A3,L1,LC1,LC3,M1,M3)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    26-Feb-2016 22:57:17

t2 = cos(a1);
t3 = l1-lc1;
t4 = sin(a1);
t5 = t3.^2;
t6 = cos(a3);
t7 = lc3.^2;
t8 = sin(a3);
Js = reshape([-I1+m1.*t2.^2.*t5+m1.*t4.^2.*t5,0.0,0.0,I3+m3.*t6.^2.*t7+m3.*t7.*t8.^2],[2,2]);
