function [p1,p2,p3,p4,p5,dp1,dp2,dp3,dp4,dp5] = autoGen_twoLink_kin(x,y,q2,dx,dy,dq2,l1,l2,d1,d2)
%AUTOGEN_TWOLINK_KIN
%    [P1,P2,P3,P4,P5,DP1,DP2,DP3,DP4,DP5] = AUTOGEN_TWOLINK_KIN(X,Y,Q2,DX,DY,DQ2,L1,L2,D1,D2)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    26-Feb-2016 03:28:56

p1 = [x;y];
if nargout > 1
    t2 = l2.^2;
    t3 = sin(q2);
    t4 = l1.^2;
    t5 = cos(q2);
    t7 = l1.*l2.*t5.*2.0;
    t6 = t2+t4-t7;
    t8 = 1.0./sqrt(t6);
    t9 = t3.^2;
    t10 = 1.0./t6;
    t11 = -t2.*t9.*t10+1.0;
    t12 = sqrt(t11);
    p2 = [x+d1.*l2.*t3.*t8;y-d1.*t12];
end
if nargout > 2
    t13 = sqrt(t6);
    t16 = l2.*t5;
    t14 = l1-t16;
    t15 = 1.0./t6.^(3.0./2.0);
    t17 = sign(t14);
    t18 = t10.^(3.0./2.0);
    t19 = 1.0./t14;
    t20 = l1.*l2;
    t21 = t5.^2;
    t22 = l1.*l2.*t21;
    t26 = t4.*t5;
    t27 = t2.*t5;
    t23 = t20+t22-t26-t27;
    t24 = l1.*l2.*t3.*t8;
    p3 = [t24+x;y-l1.*t12];
end
if nargout > 3
    p4 = [x+d2.*l1.*t3.*t8;t13+y+d2.*sqrt(-t4.*t9.*t10+1.0)];
end
if nargout > 4
    p5 = [x;t13+y];
end
if nargout > 5
    dp1 = [dx;dy];
end
if nargout > 6
    dp2 = [dx+dq2.*(d1.*l2.*t5.*t8-d1.*l1.*t2.*t9.*t15);dy-d1.*dq2.*t2.*t3.*t17.*t18.*t19.*t23];
end
if nargout > 7
    dp3 = [dx+dq2.*(l1.*l2.*t5.*t8-t2.*t4.*t9.*t15);dy-dq2.*l1.*t2.*t3.*t17.*t18.*t19.*t23];
end
if nargout > 8
    t25 = l2-l1.*t5;
    dp4 = [dx+dq2.*(d2.*l1.*t5.*t8-d2.*l2.*t4.*t9.*t15);dy+dq2.*(t24+(d2.*t3.*t4.*t18.*t23.*sign(t25))./t25)];
end
if nargout > 9
    dp5 = [dx;dy+dq2.*l1.*l2.*t3.*t8];
end
