function [Pcom,dPcom] = autoGen_CoM(x,y,q2,dx,dy,dq2,l1,l2,d1,d2,m1,m2,m3,I2,I3,g)
%AUTOGEN_COM
%    [PCOM,DPCOM] = AUTOGEN_COM(X,Y,Q2,DX,DY,DQ2,L1,L2,D1,D2,M1,M2,M3,I2,I3,G)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    26-Feb-2016 03:28:55

t2 = sin(q2);
t3 = l1.^2;
t4 = l2.^2;
t5 = cos(q2);
t10 = l1.*l2.*t5.*2.0;
t6 = t3+t4-t10;
t7 = 1.0./sqrt(t6);
t8 = m1+m2+m3;
t9 = 1.0./t8;
t11 = t2.^2;
t12 = 1.0./t6;
Pcom = [t9.*(m1.*x+m2.*(x+d1.*l2.*t2.*t7)+m3.*(x+d2.*l1.*t2.*t7));t9.*(m1.*y+m3.*(y+d2.*sqrt(-t3.*t11.*t12+1.0)+sqrt(t6))+m2.*(y-d1.*sqrt(-t4.*t11.*t12+1.0)))];
if nargout > 1
    dPcom = [0.0;0.0];
end
