function [U,T] = invPend_2DoF_Energy(q1,q2,q3,dq1,dq2,dq3,l1,l2,l3,d1,d2,d3,m1,m2,m3,I1,I2,I3,g)
%INVPEND_2DOF_ENERGY
%    [U,T] = INVPEND_2DOF_ENERGY(Q1,Q2,Q3,DQ1,DQ2,DQ3,L1,L2,L3,D1,D2,D3,M1,M2,M3,I1,I2,I3,G)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    24-Jan-2016 00:47:21

t3 = cos(q1);
t4 = dq1.*l1.*t3;
t5 = cos(q2);
t2 = t4+d2.*dq2.*t5;
t12 = cos(q3);
t6 = t4+d3.*dq3.*t12+dq2.*l2.*t5;
t8 = sin(q1);
t9 = dq1.*l1.*t8;
t10 = sin(q2);
t7 = t9+d2.*dq2.*t10;
t11 = t9+d3.*dq3.*sin(q3)+dq2.*l2.*t10;
U = dq1.^2.*(I1+d1.^2.*m1).*(1.0./2.0)+I2.*dq2.^2.*(1.0./2.0)+I3.*dq3.^2.*(1.0./2.0)+m2.*t2.^2.*(1.0./2.0)+m2.*t7.^2.*(1.0./2.0)+m3.*t6.^2.*(1.0./2.0)+m3.*t11.^2.*(1.0./2.0);
if nargout > 1
    t13 = l1.*t3;
    T = g.*m2.*(t13+d2.*t5)+g.*m3.*(t13+d3.*t12+l2.*t5)+d1.*g.*m1.*t3;
end
