function [p1,p2,p3,dp1,dp2,dp3] = invPend_3link_kin(q1,q2,q3,dq1,dq2,dq3,l1,l2,l3)
%INVPEND_3LINK_KIN
%    [P1,P2,P3,DP1,DP2,DP3] = INVPEND_3LINK_KIN(Q1,Q2,Q3,DQ1,DQ2,DQ3,L1,L2,L3)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    24-Jan-2016 00:47:21

t2 = sin(q1);
t3 = l1.*t2;
t4 = cos(q1);
t5 = l1.*t4;
p1 = [t3;t5];
if nargout > 1
    t6 = sin(q2);
    t7 = l2.*t6;
    t8 = cos(q2);
    t9 = l2.*t8;
    p2 = [t3+t7;t5+t9];
end
if nargout > 2
    t10 = dq1.*l1.*t4;
    t11 = dq2.*l2.*t8;
    t12 = cos(q3);
    t13 = sin(q3);
    p3 = [t3+t7+l3.*t13;t5+t9+l3.*t12];
end
if nargout > 3
    dp1 = [t10;-dq1.*l1.*t2];
end
if nargout > 4
    dp2 = [t10+t11;-dq1.*l1.*t2-dq2.*l2.*t6];
end
if nargout > 5
    dp3 = [t10+t11+dq3.*l3.*t12;-dq1.*l1.*t2-dq2.*l2.*t6-dq3.*l3.*t13];
end
