function [D_mtx,C_mtx,G_vec,B_mtx] = invPend_3link_EOM_mtxs(q1,q2,q3,dq1,dq2,dq3,u2,u3,l1,l2,l3,d1,d2,d3,m1,m2,m3,I1,I2,I3,g)
%INVPEND_3LINK_EOM_MTXS
%    [D_MTX,C_MTX,G_VEC,B_MTX] = INVPEND_3LINK_EOM_MTXS(Q1,Q2,Q3,DQ1,DQ2,DQ3,U2,U3,L1,L2,L3,D1,D2,D3,M1,M2,M3,I1,I2,I3,G)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    24-Jan-2016 00:47:19

t2 = l1.^2;
t3 = q1-q2;
t4 = cos(t3);
t5 = d2.*m2;
t6 = l2.*m3;
t7 = t5+t6;
t8 = l1.*t4.*t7;
t9 = q1-q3;
t10 = cos(t9);
t11 = d3.*l1.*m3.*t10;
t12 = q2-q3;
t13 = cos(t12);
t14 = d3.*l2.*m3.*t13;
D_mtx = reshape([I1+m2.*t2+m3.*t2+d1.^2.*m1,t8,t11,t8,I2+d2.^2.*m2+l2.^2.*m3,t14,t11,t14,I3+d3.^2.*m3],[3,3]);
if nargout > 1
    t15 = sin(t3);
    t16 = sin(t9);
    t17 = sin(t12);
    C_mtx = reshape([0.0,-dq1.*l1.*t7.*t15,-d3.*dq1.*l1.*m3.*t16,dq2.*l1.*t7.*t15,0.0,-d3.*dq2.*l2.*m3.*t17,d3.*dq3.*l1.*m3.*t16,d3.*dq3.*l2.*m3.*t17,0.0],[3,3]);
end
if nargout > 2
    G_vec = [-g.*sin(q1).*(d1.*m1+l1.*m2+l1.*m3);-g.*t7.*sin(q2);-d3.*g.*m3.*sin(q3)];
end
if nargout > 3
    B_mtx = reshape([1.0,-1.0,0.0,0.0,1.0,-1.0],[3,2]);
end
